apiVersion: v1
kind: Service
metadata:
  name: test-api-svc
  namespace: blue-green-deployment
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: test-api
    env: blue
  type: ClusterIP
